# Generated by Django 4.0.2 on 2022-02-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddingCourse',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('coursecode', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('marksid', models.AutoField(primary_key=True, serialize=False)),
                ('marksname', models.CharField(max_length=20)),
                ('marksvalue', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('moduleid', models.AutoField(primary_key=True, serialize=False)),
                ('modulename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteringTeachersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facname', models.CharField(max_length=60)),
                ('facusername', models.CharField(max_length=60)),
                ('facpassword', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterid', models.AutoField(primary_key=True, serialize=False)),
                ('semestername', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('seriesid', models.AutoField(primary_key=True, serialize=False)),
                ('seriesname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('settingsid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('questionsnumber', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateTable',
            fields=[
                ('templateid', models.AutoField(primary_key=True, serialize=False)),
                ('sections', models.CharField(max_length=10)),
                ('totalmarks', models.IntegerField(default=2, max_length=20)),
                ('totalquestions', models.IntegerField(max_length=20)),
                ('questionspermodule', models.IntegerField(max_length=20)),
                ('marksvalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.marks')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedCoursetoGenerate',
            fields=[
                ('selectedid', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(default='January', max_length=100)),
                ('year', models.CharField(default=2022, max_length=4)),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.addingcourse')),
                ('moduleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.modules')),
                ('seriesname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminside.series')),
            ],
        ),
        migrations.CreateModel(
            name='PrevPDF',
            fields=[
                ('previd', models.AutoField(primary_key=True, serialize=False)),
                ('prevpdf', models.FileField(upload_to='Settings')),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.addingcourse')),
            ],
        ),
        migrations.CreateModel(
            name='MappingCourse',
            fields=[
                ('mcid', models.AutoField(primary_key=True, serialize=False)),
                ('questionlimit', models.IntegerField(default=5)),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.addingcourse')),
                ('facname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.registeringteacherstable')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPDFs',
            fields=[
                ('generatedid', models.AutoField(primary_key=True, serialize=False)),
                ('questionspdf', models.FileField(upload_to='QuestionPaper')),
                ('coursename', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminside.addingcourse')),
            ],
        ),
        migrations.CreateModel(
            name='FinalQuestions',
            fields=[
                ('finalQuesid', models.AutoField(primary_key=True, serialize=False)),
                ('selectedques', models.CharField(max_length=1000)),
                ('moduleid', models.CharField(max_length=20)),
                ('coursename', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminside.addingcourse')),
                ('marksvalue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminside.marks')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentlyLoggedIn',
            fields=[
                ('clid', models.AutoField(primary_key=True, serialize=False)),
                ('facusername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.registeringteacherstable')),
            ],
        ),
        migrations.CreateModel(
            name='AddQn',
            fields=[
                ('addqnid', models.AutoField(primary_key=True, serialize=False)),
                ('type_qn', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('courseid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminside.addingcourse')),
                ('facusername', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='adminside.registeringteacherstable')),
                ('marksvalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.marks')),
                ('modulename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.modules')),
            ],
        ),
        migrations.AddField(
            model_name='addingcourse',
            name='semestername',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adminside.semester'),
        ),
    ]
