# Generated by Django 4.0.2 on 2022-02-25 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparePDFs',
            fields=[
                ('compareid', models.AutoField(primary_key=True, serialize=False)),
                ('questionspdf', models.FileField(upload_to='DisplaytoCompare')),
                ('prevpdf', models.FileField(upload_to='DisplaytoCompare')),
            ],
        ),
        migrations.AddField(
            model_name='finalquestions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Settings'),
        ),
        migrations.CreateModel(
            name='SelectedCoursetoAdd',
            fields=[
                ('selectedid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.addingcourse')),
                ('modulename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.modules')),
            ],
        ),
    ]
