# Generated by Django 4.0.2 on 2022-02-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_convertedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparePDF',
            fields=[
                ('compareid', models.AutoField(primary_key=True, serialize=False)),
                ('newpdflink', models.CharField(max_length=100)),
                ('oldpdflink', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ComparePDFs',
        ),
    ]
